<?php
// Update : 2018-10-22

require_once __DIR__."/class.eval.inc";
require_once __DIR__."/class.courses.inc";
require_once __DIR__."/class.grades.inc";
require_once __DIR__."/class.housing.inc";
require_once __DIR__."/class.mails.inc";
require_once __DIR__."/class.password.inc";
require_once __DIR__."/class.reidhall.inc";
require_once __DIR__."/class.stage.inc";
require_once __DIR__."/class.student.inc";
require_once __DIR__."/class.univ.inc";
require_once __DIR__."/class.univ_reg.inc";
require_once __DIR__."/class.users.inc";
require_once __DIR__."/../../vendor/phpmailer/phpmailer/src/PHPMailer.php";
?>
